import type { Locale } from "@/lib/i18n";

type AnyCopy = Record<string, any>;

const HOME: Record<Locale, AnyCopy> = {
  fa: { est: "تأسیس ۱۳۴۸", values: [["اصالت باغی", "از باغ‌های اصیل قزوین و بویین‌زهرا."], ["کنترل کیفیت", "سه‌مرحله رنگ، رطوبت و اندازه."], ["قیمت شفاف", "تابلوی زنده با تاریخچه و اندیکاتور."], ["عمده و صادرات", "بسته‌بندی صادراتی و برند شخصی."]], moversK: "حرکات بازار", movers: "پرشتاب‌ترین‌های امروز", fullAnalysis: "تحلیل کامل ←", premiumK: "محصولات ممتاز", premium: "خلال پسته، افتخار خانه", premiumBody: "دو نگین اصلی بازار ما، برگرفته از باغ‌های قزوین و بویین‌زهرا؛ محصولاتی که سال‌ها اعتبار تجارت خانوادگی درج سبز بر آن استوار است.", othersK: "سایر محصولات", others: "مکمل‌های سفره خشکبار", allProducts: "همه محصولات ←", wholesaleK: "فروش عمده و صادراتی", wholesale: "شریک تجاری قابل اعتماد", wholesaleBody: "برای قنادان، صنایع غذایی و صادرکنندگان؛ شرایط اختصاصی خرید عمده، تضمین کیفیت و قرارداد سالانه.", terms: "شرایط فروش عمده", contact: "تماس با ما" },
  en: { est: "Est. 1969", values: [["Orchard provenance", "From established orchards in Qazvin and Buin Zahra."], ["Quality control", "Three-stage colour, moisture and size checks."], ["Transparent pricing", "A live board with history and indicators."], ["Wholesale & export", "Export packaging and private labelling."]], moversK: "Market movers", movers: "Today's fastest movers", fullAnalysis: "Full analysis →", premiumK: "Premium products", premium: "Pistachio slivers, our signature", premiumBody: "Two leading products from the orchards of Qazvin and Buin Zahra, backed by generations of family trading expertise.", othersK: "Other products", others: "The wider nut collection", allProducts: "All products →", wholesaleK: "Wholesale & export", wholesale: "A reliable trading partner", wholesaleBody: "Dedicated wholesale terms, quality assurance and annual contracts for confectioners, manufacturers and exporters.", terms: "Wholesale terms", contact: "Contact us" },
  ar: { est: "تأسست عام ١٩٦٩", values: [["أصل البستان", "من بساتين قزوين وبوئين زهرا الأصيلة."], ["ضبط الجودة", "فحص اللون والرطوبة والحجم على ثلاث مراحل."], ["سعر شفاف", "لوحة مباشرة مع السجل والمؤشرات."], ["الجملة والتصدير", "تعبئة تصديرية وعلامة خاصة."]], moversK: "حركة السوق", movers: "الأسرع حركة اليوم", fullAnalysis: "التحليل الكامل ←", premiumK: "منتجات ممتازة", premium: "شرائح الفستق، عنوان خبرتنا", premiumBody: "منتجان رائدان من بساتين قزوين وبوئين زهرا تدعمهما خبرة أجيال في تجارة العائلة.", othersK: "منتجات أخرى", others: "مجموعة المكسرات المتكاملة", allProducts: "كل المنتجات ←", wholesaleK: "الجملة والتصدير", wholesale: "شريك تجاري موثوق", wholesaleBody: "شروط جملة خاصة وضمان جودة وعقود سنوية لأصحاب الحلويات والمصانع والمصدّرين.", terms: "شروط البيع بالجملة", contact: "اتصل بنا" },
};

const SHELL: Record<Locale, AnyCopy> = {
  fa: { aria: "بازکردن پوسته پسته و دیدن سه مسیر", title: "سه مسیر خانه‌ی سبز", body: "پوسته را باز کنید و مسیر خود را انتخاب کنید: چشیدن، اصالت باغ یا تجارت.", paths: [["آیین چشیدن", "آیین مصرف و ترکیب‌های پیشنهادی"], ["اصالت باغ", "از باغ تا بسته و شناسنامه محصول"], ["تجارت", "عمده، صادرات و تابلوی قیمت"]] },
  en: { aria: "Open the pistachio shell and discover three paths", title: "Three paths through Darj Sabz", body: "Open the shell and choose your path: tasting, orchard provenance or trade.", paths: [["Tasting ritual", "Serving rituals and pairing suggestions"], ["Orchard provenance", "From orchard to pack and product passport"], ["Trade", "Wholesale, export and the price board"]] },
  ar: { aria: "افتح قشرة الفستق واكتشف ثلاثة مسارات", title: "ثلاثة مسارات في درج سبز", body: "افتح القشرة واختر مسارك: التذوق أو أصل البستان أو التجارة.", paths: [["طقوس التذوق", "طرق التقديم واقتراحات التنسيق"], ["أصل البستان", "من البستان إلى العبوة وشهادة المنتج"], ["التجارة", "الجملة والتصدير ولوحة الأسعار"]] },
};

const MARKET: Record<Locale, AnyCopy> = {
  fa: { ranges: ["۱ه", "۱م", "۳م", "۶م", "۱س", "کل"], noData: "داده‌ای برای این بازه ثبت نشده است", indicators: "اندیکاتورها", closeIndicators: "بستن اندیکاتورها", noDataLong: "برای این محصول در بازه انتخابی داده‌ای ثبت نشده است.", chooseLonger: "بازه بلندتری انتخاب کنید یا قیمت را از پنل مدیریت ثبت کنید.", volume: "حجم معاملات", signal: "سیگنال", histogram: "هیستوگرام", high: "بالاترین", low: "پایین‌ترین", avgVolume: "میانگین حجم", open: "باز", close: "بسته", chartStyles: ["شمعی", "هیکن‌آشی", "خطی", "ناحیه‌ای"], heatmap: "نقشه بازار", heatmapBody: "وزن قیمت و تغییرات روز", down: "نزول", up: "صعود", health: "سلامت بازار", overall: "امتیاز کلی", outOf: "از ۱۰۰", scores: ["روند", "شتاب", "ثبات", "نقدشوندگی", "کیفیت", "ارزندگی"] },
  en: { ranges: ["1W", "1M", "3M", "6M", "1Y", "All"], noData: "No data recorded for this period", indicators: "Indicators", closeIndicators: "Close indicators", noDataLong: "No data has been recorded for this product in the selected period.", chooseLonger: "Choose a longer period or add a price in the admin panel.", volume: "Trading volume", signal: "Signal", histogram: "Histogram", high: "High", low: "Low", avgVolume: "Average volume", open: "Open", close: "Close", chartStyles: ["Candles", "Heikin-Ashi", "Line", "Area"], heatmap: "Market heatmap", heatmapBody: "Price weight and daily change", down: "Down", up: "Up", health: "Market health", overall: "Overall score", outOf: "out of 100", scores: ["Trend", "Momentum", "Stability", "Liquidity", "Quality", "Value"] },
  ar: { ranges: ["١أ", "١ش", "٣ش", "٦ش", "١س", "الكل"], noData: "لا توجد بيانات مسجلة لهذه الفترة", indicators: "المؤشرات", closeIndicators: "إغلاق المؤشرات", noDataLong: "لا توجد بيانات مسجلة لهذا المنتج في الفترة المحددة.", chooseLonger: "اختر فترة أطول أو أضف سعراً من لوحة الإدارة.", volume: "حجم التداول", signal: "الإشارة", histogram: "المدرج", high: "الأعلى", low: "الأدنى", avgVolume: "متوسط الحجم", open: "الافتتاح", close: "الإغلاق", chartStyles: ["شموع", "هيكن آشي", "خطي", "مساحي"], heatmap: "خريطة السوق", heatmapBody: "وزن السعر والتغير اليومي", down: "هبوط", up: "صعود", health: "صحة السوق", overall: "النتيجة الإجمالية", outOf: "من ١٠٠", scores: ["الاتجاه", "الزخم", "الاستقرار", "السيولة", "الجودة", "القيمة"] },
};

export const homeCopy = (l: Locale) => HOME[l];
export const shellCopy = (l: Locale) => SHELL[l];
export const marketCopy = (l: Locale) => MARKET[l];