/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as TasteRouteImport } from './routes/taste'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OriginRouteImport } from './routes/origin'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const TasteRoute = TasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginRoute = OriginRouteImport.update({
  id: '/origin',
  path: '/origin',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/licenses': typeof LicensesRoute
  '/market': typeof MarketRoute
  '/news': typeof NewsRoute
  '/origin': typeof OriginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taste': typeof TasteRoute
  '/wholesale': typeof WholesaleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/licenses': typeof LicensesRoute
  '/market': typeof MarketRoute
  '/news': typeof NewsRoute
  '/origin': typeof OriginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taste': typeof TasteRoute
  '/wholesale': typeof WholesaleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/journal': typeof JournalIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/licenses': typeof LicensesRoute
  '/market': typeof MarketRoute
  '/news': typeof NewsRoute
  '/origin': typeof OriginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taste': typeof TasteRoute
  '/wholesale': typeof WholesaleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/compare'
    | '/contact'
    | '/licenses'
    | '/market'
    | '/news'
    | '/origin'
    | '/sitemap.xml'
    | '/taste'
    | '/wholesale'
    | '/journal/$slug'
    | '/products/$slug'
    | '/journal/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/compare'
    | '/contact'
    | '/licenses'
    | '/market'
    | '/news'
    | '/origin'
    | '/sitemap.xml'
    | '/taste'
    | '/wholesale'
    | '/journal/$slug'
    | '/products/$slug'
    | '/journal'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/compare'
    | '/contact'
    | '/licenses'
    | '/market'
    | '/news'
    | '/origin'
    | '/sitemap.xml'
    | '/taste'
    | '/wholesale'
    | '/journal/$slug'
    | '/products/$slug'
    | '/journal/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AnalysisRoute: typeof AnalysisRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  LicensesRoute: typeof LicensesRoute
  MarketRoute: typeof MarketRoute
  NewsRoute: typeof NewsRoute
  OriginRoute: typeof OriginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasteRoute: typeof TasteRoute
  WholesaleRoute: typeof WholesaleRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taste': {
      id: '/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof TasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origin': {
      id: '/origin'
      path: '/origin'
      fullPath: '/origin'
      preLoaderRoute: typeof OriginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AnalysisRoute: AnalysisRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  LicensesRoute: LicensesRoute,
  MarketRoute: MarketRoute,
  NewsRoute: NewsRoute,
  OriginRoute: OriginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasteRoute: TasteRoute,
  WholesaleRoute: WholesaleRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
